Fix Concurrent Modification Exception caused by removeOldContext
```
[18:18:38] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Exception in world tick
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:4628) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:4035) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.util.ConcurrentModificationException
	at gnu.trove.impl.hash.THashIterator.nextIndex(THashIterator.java:156) ~[THashIterator.class:3.0.3]
	at gnu.trove.impl.hash.THashIterator.hasNext(THashIterator.java:103) ~[THashIterator.class:3.0.3]
	at fr.iamacat.optimizationsandtweaks.utils.optimizationsandtweaks.tidychunkbackport.TidyChunkBackportWorldContext.removeOldContext(TidyChunkBackportWorldContext.java:60) ~[TidyChunkBackportWorldContext.class:?]
	at fr.iamacat.optimizationsandtweaks.eventshandler.TidyChunkBackportEventHandler.injectInWorldTick(TidyChunkBackportEventHandler.java:73) ~[TidyChunkBackportEventHandler.class:?]
	at net.minecraft.world.World.handler$zzc000$optimizationsandtweaks$onTickInject(World.java:51977) ~[ahb.class:?]
	at net.minecraft.world.World.func_72835_b(World.java:2669) ~[ahb.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:66) ~[bjf.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:4617) ~[bao.class:?]
	... 9 more
```